import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

export default defineConfig({
  plugins: [vue()],
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
  resolve: {
    // In Wails dev mode, the bindings are generated by `wails dev`
    // and available at runtime. For production build, we don't need them.
  },
})
