// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EmitFiles() {
  return window['go']['main']['App']['EmitFiles']();
}

export function GetFilePaths() {
  return window['go']['main']['App']['GetFilePaths']();
}

export function GetFileTitle(arg1) {
  return window['go']['main']['App']['GetFileTitle'](arg1);
}

export function GetFiles() {
  return window['go']['main']['App']['GetFiles']();
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}
